import React, { useEffect, useMemo, useRef } from "react";
import type { Job } from "../lib/types.js";
import { formatNumber, reasoningLabel, verificationLabel } from "../lib/format.js";
export function ExecutionPanel({ job }: { job: Job }) {
  const execution = job.execution;
  const consoleRef = useRef<HTMLPreElement>(null);
  const consoleText = useMemo(() => formatCodexConsole(job.output ?? ""), [job.output]);
  useEffect(() => { if (job.status === "RUNNING") consoleRef.current?.scrollTo({ top: consoleRef.current.scrollHeight }); }, [consoleText, job.status]);
  const compactConfirmed = execution?.events.some(event => event.title === "Codex /compact confirmed");
  const shared = Boolean(execution?.group && execution.group.size > 1);
  return <div className="execution-panel">
    <div className="execution-head"><div><span className={job.status === "RUNNING" ? "pulse" : "pulse still"}/><div><p className="panel-label">LIVE EXECUTION</p><h3>{execution?.phase.toLowerCase().replace("_", " ") ?? "Error"}</h3></div></div>{execution && <div className="runtime-meta"><span><small>{job.status === "RUNNING" ? "CURRENT MODEL" : "LAST MODEL"}</small>{execution.model}</span><span><small>{job.status === "RUNNING" ? "CURRENT REASONING" : "LAST REASONING"}</small>{reasoningLabel(execution.reasoning)}</span><span><small>PROCESS</small>{execution.pid ? `PID ${execution.pid}` : "—"}</span><span><small>STARTED</small>{new Date(execution.startedAt).toLocaleTimeString()}</span></div>}</div>
    {execution && <div className="execution-proof"><b>✓ Codex model routing</b><span>{execution.model}</span><span>reasoning: {reasoningLabel(execution.reasoning)}</span>{shared && <strong>shared prompt · {execution.group!.size} tasks</strong>}{compactConfirmed && <strong>/compact confirmed by Codex app-server</strong>}</div>}
    {job.error && <div className="execution-error"><b>Execution error</b><span>{job.error}</span></div>}
    {execution && job.status !== "RUNNING" && <><div className="status-report"><div><small>FINAL STATUS</small><b>{verificationLabel(execution.verification)}</b></div><div><small>{shared ? "GROUP INPUT TOKENS" : "TASK INPUT TOKENS"}</small><b>{formatNumber(execution.usage?.input_tokens)}</b></div><div><small>CACHED INPUT</small><b>{formatNumber(execution.usage?.cached_input_tokens)}</b></div><div><small>{shared ? "GROUP OUTPUT TOKENS" : "TASK OUTPUT TOKENS"}</small><b>{formatNumber(execution.usage?.output_tokens)}</b></div><div><small>ACCOUNT TODAY</small><b>{execution.accountUsage?.unavailableReason ? "Unavailable" : formatNumber(execution.accountUsage?.todayTokens)}</b></div><div><small>ACCOUNT LIFETIME</small><b>{execution.accountUsage?.unavailableReason ? "Unavailable" : formatNumber(execution.accountUsage?.lifetimeTokens)}</b></div><div><small>COMPACTION</small><b>{execution.compactedAfterTask ? "Completed" : "Not due"}</b></div></div><p className="codex-usage-note">Task tokens are summed across Codex turns. Account figures are a best-effort, account-wide Codex status snapshot{shared ? "; task token totals are shared by this prompt group." : "."}{execution.accountUsage?.unavailableReason ? ` ${execution.accountUsage.unavailableReason}` : ""}</p></>}
    {execution?.metrics && job.status !== "RUNNING" && <section className="execution-metrics"><p className="panel-label">EXECUTION ECONOMY</p><div><span><small>JEV TOKEN ESTIMATE</small><b>{formatNumber(execution.metrics.estimatedTokens)}</b></span><span><small>ACTUAL CODEX TOKENS</small><b>{formatNumber(execution.metrics.actualTokens)}</b></span><span><small>TURNS</small><b>{execution.metrics.turns}</b></span><span><small>REPAIRS</small><b>{execution.metrics.repairs}</b></span><span><small>VALIDATION STOP</small><b>{execution.metrics.stoppedAfterValidation ? "Yes" : "No"}</b></span><span className="execution-routes"><small>MODEL ROUTES</small><b>{execution.metrics.routes.map(route => `${route.model} / ${reasoningLabel(route.reasoning)}`).join(" → ")}</b></span></div><p>Estimate is a planning signal based on ticket scope, context, and initial reasoning. Actual tokens are reported by Codex across all turns{shared ? " and shared by this prompt group" : ""}.</p></section>}
    <div className="live-console"><div className="console-bar"><span><i/><i/><i/></span><b>CODEX LIVE CONSOLE</b><small>{job.status === "RUNNING" ? "STREAMING" : job.status}</small></div><pre ref={consoleRef}>{consoleText || "Waiting for the first Codex event…"}<span className="console-cursor">▋</span></pre></div>
    <div className="timeline">{execution?.events.map(event => <div className={`event ${event.kind} ${event.title.includes("/compact") ? "event-compact" : ""}`} key={event.id}><span className="event-line"/><span className={`event-icon ${event.status ?? ""}`}>{event.kind === "command" ? ">_" : event.kind === "file" ? "◇" : event.kind === "error" ? "!" : event.kind === "reasoning" ? "✦" : "✓"}</span><div><div className="event-title"><b>{event.title}</b><time>{new Date(event.timestamp).toLocaleTimeString()}</time></div>{event.detail && <pre>{event.detail}</pre>}</div></div>)}</div>
    {job.output && <details className="raw-output"><summary>View raw Codex JSONL output</summary><pre>{job.output}</pre></details>}
  </div>;
}

function formatCodexConsole(output: string) { return output.split("\n").filter(Boolean).map(line => { if (/^Reading additional input from stdin/i.test(line)) return ""; try { const event = JSON.parse(line) as any; const item = event.item ?? {}; if (event.type === "thread.started") return `● Session started  ${event.thread_id ?? ""}`; if (event.type === "turn.started") return "✦ Codex is reading the project and planning…"; if (event.type === "turn.completed") return `✓ Turn completed  ${JSON.stringify(event.usage ?? {})}`; if (event.type === "turn.failed" || event.type === "error") return `! ERROR  ${JSON.stringify(event.error ?? event.message ?? event)}`; if (item.type === "command_execution") { const command = String(item.command ?? ""); const result = String(item.aggregated_output ?? "").trim().slice(-4000); return item.status === "in_progress" ? `$ ${command}` : result || `✓ Command finished with exit code ${String(item.exit_code ?? 0)}`; } if (item.type === "agent_message") return String(item.text ?? ""); if (/reason/i.test(item.type ?? "")) return `◆ ${String(item.text ?? "Reasoning…")}`; if (/file|change|patch/i.test(item.type ?? "")) return `◇ Files changed  ${JSON.stringify(item.changes ?? item.path ?? item).slice(0, 4000)}`; return ""; } catch { return line.slice(0, 4000); } }).filter(Boolean).join("\n\n"); }
